#!/bin/bash

RCMD="Rscript"
TMPDIR="$HOME/share/tmp"
QUEUE="jrf.q"
LOGDIR=log/Rshell

while getopts "e:sm:n:l:p:" opt; do
  case $opt in
    l)
    LOGDIR=$OPTARG
      ;;
    e)
    R=$OPTARG
      ;;
    m)
    MEM=$OPTARG
      ;;
    p)
    PARALLEL=$OPTARG
      ;;
    n)
    NAME=$OPTARG
      ;;
    s)
    SGE=true
      ;;
    \:)
      echo "Argument missing: -$OPTARG" >&2
      exit -1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit -1
      ;;
  esac
done

echo "#---------------------------------";

if [[ $PARALLEL -gt 1 ]]; then
    PE="-pe smp $PARALLEL"
fi

umask 022
 
if [[ -n "$R" ]]; then 
    TMP=$(mktemp --tmpdir=${TMPDIR})
    #TMP=$(mktemp -t x)
    trap "{ rm -f ${TMP}; exit 255;  }" SIGINT
    echo "Sys.umask(022)" > ${TMP}
    echo "${R}" >> ${TMP}
    if [[ -n "$SGE" ]]; then
        mkdir -p $LOGDIR
        qrsh -cwd -V -now n -q $QUEUE -N X$NAME $PE -l virtual_free=$MEM,h_vmem=$MEM "umask 022; ${RCMD} ${TMP}" 2>&1 && RET_CODE=$? | tee $LOGDIR/$NAME.log
        #echo "ret code:  $?"
        RET_CODE=$?
    else
        #echo $MEM
        $RCMD ${TMP}
        RET_CODE=$?
    fi
    rm -f ${TMP}
    exit ${RET_CODE}
else
    echo "Undefined script" >&2
    exit -1
fi

