#!/bin/bash

RCMD="R --vanilla --no-readline --quiet"
TMPDIR="$HOME/share/tmp"
QUEUE="jrf.q"
LOGDIR=log/Rshell

while getopts "e:sm:n:l:p:" opt; do
  case $opt in
    l)
    LOGDIR=$OPTARG
      ;;
    e)
    R=$OPTARG
      ;;
    m)
    MEM=$OPTARG
      ;;
    p)
    PARALLEL=$OPTARG
      ;;
    n)
    NAME=$OPTARG
      ;;
    s)
    SGE=true
      ;;
    \:)
      echo "Argument missing: -$OPTARG" >&2
      exit -1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit -1
      ;;
  esac
done

if [[ -n "$PARALLEL" ]]; then
    PE="-pe smp $PARALLEL"
fi
 
if [[ -n "$R" ]]; then 
    TMP=$(mktemp --tmpdir=${TMPDIR})
    #TMP=$(mktemp -t x)
    trap "{ rm -f ${TMP}; exit 255;  }" SIGINT
    echo "${R}" > ${TMP}
    if [[ -n "$SGE" ]]; then
        mkdir -p $LOGDIR
        qrsh -cwd -V -now n -q $QUEUE -N X$NAME $PE -l virtual_free=$MEM,h_vmem=$MEM "${RCMD} < ${TMP}" &> $LOGDIR/$NAME.log
    else
        echo $MEM
        $RCMD < ${TMP}
    fi
    rm -f ${TMP}
else
    echo "Undefined script" >&2
    exit -1
fi
